version: '2'
services:
  consumer:
    image: ibmcom/velocity-consumer:latest
    ports:
      - "6004:6004"
    links:
      - database
    environment:
      - MONGO_URL=mongodb://database:27017/meteor
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUMER_URL=http://${URL_DOMAIN}:6004
      # Logging level. Possible values, all < debug < info < warn < error < fatal < off
      - LOG_LEVEL=error
  ui:
    image: ibmcom/velocity-ui:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    environment:
      # ROOT_URL, the URL users will be accessing the UI with.
      - ROOT_URL=https://${URL_DOMAIN}:443
      # DDP_DEFAULT_CONNECTION_URL same as ROOT_URL
      - DDP_DEFAULT_CONNECTION_URL=https://${URL_DOMAIN}:443
      - MONGO_URL=mongodb://database:27017/meteor
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - ADMIN_PASSWORD=admin
      - ACCESS_KEY=${ACCESS_KEY}
      - COMPOSE_VERSION=1.0.0
      # Logging level. Possible values, all < debug < info < warn < error < fatal < off
      - LOG_LEVEL=error
  database:
    image:  mongo:3.2
    command: mongod --quiet --logpath=/dev/null
    volumes:
      - mongodb:/data/db
    # Expose mongo port only for debugging or if you want to browse using robomongo
    # ports:
    #   - "27017:27017"
volumes:
  mongodb:
    external:
      name: velocity-mongo
